# Generated by Django 4.1.4 on 2023-01-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('dept_id', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
    ]
