# Generated by Django 4.1.4 on 2023-01-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('Er_no', models.IntegerField()),
                ('Address', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
                ('choice', models.CharField(choices=[('Subject 1', 'Data Science'), ('Subject 2', 'AI/ML'), ('Subject 3', 'Python')], max_length=100)),
            ],
        ),
    ]
