# Generated by Django 4.1.4 on 2023-01-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='dept_id',
        ),
        migrations.DeleteModel(
            name='dept',
        ),
    ]
