# Generated by Django 4.1.4 on 2023-01-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_register_alter_student_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='phonw',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.TextField(),
        ),
    ]
