# Generated by Django 4.1.4 on 2023-02-22 17:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_user_profile_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_profile',
            new_name='Profile',
        ),
    ]
